---
kind: pipeline
name: docker-6.2

trigger:
  branch:
    - release-6.2

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: fetch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: docker
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/cann6.2.RC2-py310.dockerfile
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/ascend-infer-310b:23.0.RC2-arm64
      repo: wod/cann
      version: "6.2.RC2-py310"
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: docker-6.2-torch1.11

trigger:
  branch:
    - release-6.2-torch1.11

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: fetch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: docker
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/cann6.2.RC2-py310-torch111.dockerfile
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/pytorch-modelzoo:23.0.RC2-1.11.0
      repo: wod/cann
      version: "6.2.RC2-py310-torch111"
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: cann-8.0

trigger:
  branch:
    - cann-8.0

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: fetch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: docker
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/cann8.0.RC3.dockerfile
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/cann:py310
      repo: wod/cann
      version: "8.0.RC3-py310"
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: cann-8.0-torch

trigger:
  branch:
    - cann-8.0-torch

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: fetch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: docker
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/cann8.0.RC3-torch240.dockerfile
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/cann:8.0.RC3-py310
      repo: wod/cann
      version: "8.0.RC3-py310-torch240"
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: cann-8.0-vnc

trigger:
  branch:
    - cann-8.0-vnc

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: fetch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: docker
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/cann8.0.RC3-vnc116.dockerfile
      base: registry.ali.wodcloud.com/wod/cann:py310-vnc116
      repo: wod/cann
      version: "8.0.RC3-py310-vnc116"
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: py310

trigger:
  branch:
    - py310

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: fetch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: docker
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/py310.dockerfile
      base: registry.ali.wodcloud.com/wod/debian:12-arm64
      repo: wod/cann
      version: py310
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: py310-vnc116

trigger:
  branch:
    - py310-vnc116

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: fetch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: docker
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/py310-vnc116.dockerfile
      base: registry.ali.wodcloud.com/wod/kasmweb:debian-bookworm-desktop-v1.16.0-arm64
      repo: wod/cann
      version: py310-vnc116
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: cann-8.0-kernel910b

trigger:
  branch:
    - cann-8.0-kernel910b

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: fetch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: docker
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/cann8.0.RC3-kernel910b.dockerfile
      base: registry.ali.wodcloud.com/wod/cann:py310
      repo: wod/cann
      version: "8.0.RC3-py310-kernel910b"
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: cann-8.0-kernel910b-vnc

trigger:
  branch:
    - cann-8.0-kernel910b-vnc

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: fetch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: docker
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/cann8.0.RC3-kernel910b-vnc116.dockerfile
      base: registry.ali.wodcloud.com/wod/cann:py310-vnc116
      repo: wod/cann
      version: "8.0.RC3-py310-kernel910b-vnc116"
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: harbor

trigger:
  branch:
    - master

clone:
  disable: true

steps:
  - name: harbor-6.2
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    settings:
      source: registry-vpc.cn-qingdao.aliyuncs.com/wod/cann:6.2.RC2-py310
      target: registry-vpc.cn-qingdao.aliyuncs.com/wod/cann:6.2-py310
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-6.2-torch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    settings:
      source: registry-vpc.cn-qingdao.aliyuncs.com/wod/cann:6.2.RC2-py310-torch111
      target: registry-vpc.cn-qingdao.aliyuncs.com/wod/cann:6.2-py310-torch111
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-8.0
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    settings:
      source: registry-vpc.cn-qingdao.aliyuncs.com/wod/cann:910b-8.0.RC3-py310
      target: registry-vpc.cn-qingdao.aliyuncs.com/wod/cann:910b-8.0-py310
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-8.0-torch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    settings:
      source: registry-vpc.cn-qingdao.aliyuncs.com/wod/cann:910b-8.0.RC3-py310-torch240
      target: registry-vpc.cn-qingdao.aliyuncs.com/wod/cann:910b-8.0-py310-torch240
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: secret
name: SOCKS5_PROXY
get:
  name: SOCKS5_PROXY
  path: devops-secrets

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: REGISTRY_USER_ALIYUN
  path: devops-secrets

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: REGISTRY_PASSWORD_ALIYUN
  path: devops-secrets

---
kind: secret
name: S3_ACCESS_KEY_ALIYUN
get:
  name: S3_ACCESS_KEY_ALIYUN
  path: devops-secrets

---
kind: secret
name: S3_SECRET_KEY_ALIYUN
get:
  name: S3_SECRET_KEY_ALIYUN
  path: devops-secrets
